<?php
    session_start();
    include 'INCLUDES/dbh-inc.php';
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
            <title>Demo I.C.N</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
            <link rel="stylesheet" href="CSS/style.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="JS/script.js"></script>
    </head>
<body>
    <div id="demoBox">
        <?php
            if(isset($_SESSION['u_id'])) {
                echo '<div class="userPseudo">
                    <em><h1 style="color: white; font-size: 50px;">Bienvenue<br>' .$_SESSION['u_uid']. '</h1></em>
                    </div>';
            }
        ?>
        <h2 style="text-decoration: underline; margin-top: 15%;">Languages utilisés<h2>
        <ol class="listeLang">
            <li><a href="#"> HTML</a></li>
            <li><a href="#"> CSS</a></li>
            <li><a href="#"> JAVASCRIPT<br>(avec Jquery)</a></li>
            <li><a href="#"> PHP<br>(avec MySQL)</a></li>
        </ol>
    </div>
    <div id="contenuDemo">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mi elit, mattis quis pretium in, rutrum a dui. Etiam eu sagittis turpis, vel suscipit quam. Nam vitae nunc velit. Ut ex nisi, scelerisque id sollicitudin at, tempor sed augue. Aenean condimentum elit sit amet augue hendrerit commodo. Praesent sit amet malesuada magna. Aliquam et commodo arcu. Phasellus gravida vulputate lobortis. Suspendisse id sodales mi, at auctor odio. Donec fringilla rutrum enim, vel lacinia elit imperdiet at. Vestibulum consectetur lorem quis ex consectetur, id interdum tortor iaculis. Cras iaculis ultrices odio id ultrices.

        Curabitur erat neque, ullamcorper nec ornare sit amet, euismod eu felis. Etiam scelerisque justo felis, a tempus ex dictum et. Vivamus tempor vel enim sed tincidunt. Cras vel nulla non nibh eleifend lobortis sit amet ut dui. Nam sit amet ultrices nunc. Maecenas a turpis sed sem vestibulum iaculis. Fusce ut elit ac mauris vulputate accumsan vitae ac justo. Proin viverra orci neque, condimentum viverra arcu euismod quis. Sed ornare ac metus at rutrum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla semper mi vel augue posuere vehicula. Ut ante mi, porta sed orci a, dictum iaculis ligula.

        Mauris tempor lectus dui, ac malesuada dolor tincidunt ut. Aliquam iaculis quam nec elit dignissim, non dictum tortor ornare. Suspendisse sit amet pharetra quam. Mauris ligula tortor, congue vitae accumsan rutrum, fermentum id mauris. Nulla et lorem vitae metus vulputate semper et vitae nunc. Etiam porta diam vitae diam venenatis vulputate. Phasellus sodales eget justo vitae facilisis. Fusce ultrices tortor quis rutrum maximus. Sed id lacus ac ipsum tempor efficitur. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer feugiat urna sed semper sodales. Curabitur mattis ligula faucibus ipsum aliquam, nec laoreet orci consequat. Mauris facilisis tristique orci, quis lacinia tellus fringilla id. Ut pellentesque sapien tortor, consectetur auctor sem cursus sit amet.

        Nulla porttitor odio velit, vitae euismod mauris tempor ac. Praesent ultricies hendrerit diam id ornare. Vivamus maximus libero eu felis tempor, ut pellentesque dolor laoreet. Nunc malesuada quis augue vel malesuada. Pellentesque molestie libero id vestibulum scelerisque. Donec tempus, urna at accumsan mollis, dui metus mattis quam, in tincidunt est turpis sit amet augue. Aenean non laoreet purus. Pellentesque tempor pharetra mi, scelerisque mattis odio suscipit ut. Etiam quis auctor lorem. Donec pellentesque sapien eget blandit rhoncus. Sed ut enim aliquam, mattis erat eu, ullamcorper orci. Cras eu diam et nunc faucibus hendrerit nec dignissim nulla. Vivamus eget efficitur metus, vel imperdiet sem. Ut ornare ante dapibus pulvinar pulvinar. Quisque in tincidunt metus, id egestas libero.

        Etiam metus leo, pulvinar vitae lorem a, venenatis vestibulum lorem. Phasellus scelerisque lacus eget lectus luctus volutpat. Aenean pellentesque eu nisl vel egestas. Fusce tempor erat magna, in luctus magna laoreet et. Aenean feugiat accumsan nisl, non venenatis tellus imperdiet in. Nullam euismod sapien sed sem placerat pellentesque. Sed ultrices tristique scelerisque.

        Maecenas et tellus nec odio feugiat pellentesque. Pellentesque iaculis facilisis nibh non dapibus. Nunc scelerisque nisi at iaculis ultrices. Maecenas aliquet in massa id commodo. Praesent sapien nisl, dapibus et sem vitae, vestibulum mollis enim. Nullam ut ullamcorper diam. Nam elementum dapibus ligula sit amet placerat.

        Suspendisse eu mauris dolor. Etiam fermentum augue ligula, et dignissim odio efficitur et. Mauris placerat lorem urna, vel tristique velit vulputate vitae. Vestibulum vel sem id odio finibus ultrices sit amet vitae felis. Praesent posuere ultricies erat, nec posuere purus mollis et. Donec et pharetra ipsum. Fusce vulputate nunc eros, sed maximus nisl vulputate eu. Sed aliquet lectus sed libero posuere, sed tristique mauris convallis. Quisque tincidunt risus nec metus euismod eleifend.

        Duis posuere laoreet ultrices. Aenean ut augue et odio mollis accumsan. Aliquam magna augue, semper sed magna sit amet, laoreet fringilla nibh. Vestibulum turpis nunc, semper non odio et, facilisis mollis lacus. Integer odio nunc, condimentum in ornare ac, porta vitae nulla. Vivamus mollis justo mi, at rutrum felis malesuada id. Ut congue, nisl ut ullamcorper convallis, felis dui scelerisque sem, vitae vehicula purus orci eu augue. Quisque leo massa, semper sed porttitor feugiat, tempus sed dolor. Pellentesque vestibulum diam ac nunc laoreet, ac auctor lorem ultrices. Nulla sed velit aliquet, ultricies ligula ut, blandit lectus. Morbi tincidunt consectetur tellus, ut finibus magna. Vivamus ac semper nulla, vitae pulvinar massa. Fusce varius magna non ipsum pharetra auctor vitae efficitur felis. Etiam placerat sit amet erat sit amet imperdiet. Nulla lacus metus, accumsan ut feugiat in, imperdiet sit amet urna. Mauris porttitor turpis massa.

        Donec faucibus sem a erat semper, non cursus nulla pellentesque. Aenean imperdiet arcu vestibulum est facilisis, sed aliquet metus pellentesque. Duis tellus elit, aliquet vitae vehicula a, laoreet ut mi. Pellentesque mollis turpis nisl, eget volutpat nulla sodales sit amet. Donec non quam diam. Proin vel ultrices erat, et malesuada mi. Vestibulum quis orci in justo viverra vehicula. Cras neque ex, tempor nec euismod at, tincidunt lacinia ex. Phasellus tincidunt orci in leo suscipit, et ullamcorper dolor rhoncus.

        Nam mattis sed augue in tempor. Pellentesque sapien ante, tincidunt sit amet placerat non, pulvinar in lorem. Curabitur maximus metus eget orci suscipit sodales. Donec commodo dui eu egestas venenatis. Aliquam sit amet est tincidunt, bibendum sem in, fringilla nibh. Sed nec semper lorem. Integer porttitor orci vel euismod tristique. Fusce bibendum mauris vitae vehicula ullamcorper. Praesent gravida, tellus vitae scelerisque efficitur, mauris lectus ultricies nunc, nec feugiat enim lectus et mauris. Nulla facilisi. Proin at consectetur nibh, bibendum semper dolor. Phasellus nec suscipit metus, nec blandit elit. Quisque vehicula dolor non mattis blandit. Sed tincidunt metus id ipsum gravida lobortis. Aliquam ut semper risus.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mi elit, mattis quis pretium in, rutrum a dui. Etiam eu sagittis turpis, vel suscipit quam. Nam vitae nunc velit. Ut ex nisi, scelerisque id sollicitudin at, tempor sed augue. Aenean condimentum elit sit amet augue hendrerit commodo. Praesent sit amet malesuada magna. Aliquam et commodo arcu. Phasellus gravida vulputate lobortis. Suspendisse id sodales mi, at auctor odio. Donec fringilla rutrum enim, vel lacinia elit imperdiet at. Vestibulum consectetur lorem quis ex consectetur, id interdum tortor iaculis. Cras iaculis ultrices odio id ultrices.

        Curabitur erat neque, ullamcorper nec ornare sit amet, euismod eu felis. Etiam scelerisque justo felis, a tempus ex dictum et. Vivamus tempor vel enim sed tincidunt. Cras vel nulla non nibh eleifend lobortis sit amet ut dui. Nam sit amet ultrices nunc. Maecenas a turpis sed sem vestibulum iaculis. Fusce ut elit ac mauris vulputate accumsan vitae ac justo. Proin viverra orci neque, condimentum viverra arcu euismod quis. Sed ornare ac metus at rutrum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla semper mi vel augue posuere vehicula. Ut ante mi, porta sed orci a, dictum iaculis ligula.

        Mauris tempor lectus dui, ac malesuada dolor tincidunt ut. Aliquam iaculis quam nec elit dignissim, non dictum tortor ornare. Suspendisse sit amet pharetra quam. Mauris ligula tortor, congue vitae accumsan rutrum, fermentum id mauris. Nulla et lorem vitae metus vulputate semper et vitae nunc. Etiam porta diam vitae diam venenatis vulputate. Phasellus sodales eget justo vitae facilisis. Fusce ultrices tortor quis rutrum maximus. Sed id lacus ac ipsum tempor efficitur. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer feugiat urna sed semper sodales. Curabitur mattis ligula faucibus ipsum aliquam, nec laoreet orci consequat. Mauris facilisis tristique orci, quis lacinia tellus fringilla id. Ut pellentesque sapien tortor, consectetur auctor sem cursus sit amet.

        Nulla porttitor odio velit, vitae euismod mauris tempor ac. Praesent ultricies hendrerit diam id ornare. Vivamus maximus libero eu felis tempor, ut pellentesque dolor laoreet. Nunc malesuada quis augue vel malesuada. Pellentesque molestie libero id vestibulum scelerisque. Donec tempus, urna at accumsan mollis, dui metus mattis quam, in tincidunt est turpis sit amet augue. Aenean non laoreet purus. Pellentesque tempor pharetra mi, scelerisque mattis odio suscipit ut. Etiam quis auctor lorem. Donec pellentesque sapien eget blandit rhoncus. Sed ut enim aliquam, mattis erat eu, ullamcorper orci. Cras eu diam et nunc faucibus hendrerit nec dignissim nulla. Vivamus eget efficitur metus, vel imperdiet sem. Ut ornare ante dapibus pulvinar pulvinar. Quisque in tincidunt metus, id egestas libero.

        Etiam metus leo, pulvinar vitae lorem a, venenatis vestibulum lorem. Phasellus scelerisque lacus eget lectus luctus volutpat. Aenean pellentesque eu nisl vel egestas. Fusce tempor erat magna, in luctus magna laoreet et. Aenean feugiat accumsan nisl, non venenatis tellus imperdiet in. Nullam euismod sapien sed sem placerat pellentesque. Sed ultrices tristique scelerisque.

        Maecenas et tellus nec odio feugiat pellentesque. Pellentesque iaculis facilisis nibh non dapibus. Nunc scelerisque nisi at iaculis ultrices. Maecenas aliquet in massa id commodo. Praesent sapien nisl, dapibus et sem vitae, vestibulum mollis enim. Nullam ut ullamcorper diam. Nam elementum dapibus ligula sit amet placerat.

        Suspendisse eu mauris dolor. Etiam fermentum augue ligula, et dignissim odio efficitur et. Mauris placerat lorem urna, vel tristique velit vulputate vitae. Vestibulum vel sem id odio finibus ultrices sit amet vitae felis. Praesent posuere ultricies erat, nec posuere purus mollis et. Donec et pharetra ipsum. Fusce vulputate nunc eros, sed maximus nisl vulputate eu. Sed aliquet lectus sed libero posuere, sed tristique mauris convallis. Quisque tincidunt risus nec metus euismod eleifend.

        Duis posuere laoreet ultrices. Aenean ut augue et odio mollis accumsan. Aliquam magna augue, semper sed magna sit amet, laoreet fringilla nibh. Vestibulum turpis nunc, semper non odio et, facilisis mollis lacus. Integer odio nunc, condimentum in ornare ac, porta vitae nulla. Vivamus mollis justo mi, at rutrum felis malesuada id. Ut congue, nisl ut ullamcorper convallis, felis dui scelerisque sem, vitae vehicula purus orci eu augue. Quisque leo massa, semper sed porttitor feugiat, tempus sed dolor. Pellentesque vestibulum diam ac nunc laoreet, ac auctor lorem ultrices. Nulla sed velit aliquet, ultricies ligula ut, blandit lectus. Morbi tincidunt consectetur tellus, ut finibus magna. Vivamus ac semper nulla, vitae pulvinar massa. Fusce varius magna non ipsum pharetra auctor vitae efficitur felis. Etiam placerat sit amet erat sit amet imperdiet. Nulla lacus metus, accumsan ut feugiat in, imperdiet sit amet urna. Mauris porttitor turpis massa.

        Donec faucibus sem a erat semper, non cursus nulla pellentesque. Aenean imperdiet arcu vestibulum est facilisis, sed aliquet metus pellentesque. Duis tellus elit, aliquet vitae vehicula a, laoreet ut mi. Pellentesque mollis turpis nisl, eget volutpat nulla sodales sit amet. Donec non quam diam. Proin vel ultrices erat, et malesuada mi. Vestibulum quis orci in justo viverra vehicula. Cras neque ex, tempor nec euismod at, tincidunt lacinia ex. Phasellus tincidunt orci in leo suscipit, et ullamcorper dolor rhoncus.

        Nam mattis sed augue in tempor. Pellentesque sapien ante, tincidunt sit amet placerat non, pulvinar in lorem. Curabitur maximus metus eget orci suscipit sodales. Donec commodo dui eu egestas venenatis. Aliquam sit amet est tincidunt, bibendum sem in, fringilla nibh. Sed nec semper lorem. Integer porttitor orci vel euismod tristique. Fusce bibendum mauris vitae vehicula ullamcorper. Praesent gravida, tellus vitae scelerisque efficitur, mauris lectus ultricies nunc, nec feugiat enim lectus et mauris. Nulla facilisi. Proin at consectetur nibh, bibendum semper dolor. Phasellus nec suscipit metus, nec blandit elit. Quisque vehicula dolor non mattis blandit. Sed tincidunt metus id ipsum gravida lobortis. Aliquam ut semper risus.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mi elit, mattis quis pretium in, rutrum a dui. Etiam eu sagittis turpis, vel suscipit quam. Nam vitae nunc velit. Ut ex nisi, scelerisque id sollicitudin at, tempor sed augue. Aenean condimentum elit sit amet augue hendrerit commodo. Praesent sit amet malesuada magna. Aliquam et commodo arcu. Phasellus gravida vulputate lobortis. Suspendisse id sodales mi, at auctor odio. Donec fringilla rutrum enim, vel lacinia elit imperdiet at. Vestibulum consectetur lorem quis ex consectetur, id interdum tortor iaculis. Cras iaculis ultrices odio id ultrices.

        Curabitur erat neque, ullamcorper nec ornare sit amet, euismod eu felis. Etiam scelerisque justo felis, a tempus ex dictum et. Vivamus tempor vel enim sed tincidunt. Cras vel nulla non nibh eleifend lobortis sit amet ut dui. Nam sit amet ultrices nunc. Maecenas a turpis sed sem vestibulum iaculis. Fusce ut elit ac mauris vulputate accumsan vitae ac justo. Proin viverra orci neque, condimentum viverra arcu euismod quis. Sed ornare ac metus at rutrum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla semper mi vel augue posuere vehicula. Ut ante mi, porta sed orci a, dictum iaculis ligula.

        Mauris tempor lectus dui, ac malesuada dolor tincidunt ut. Aliquam iaculis quam nec elit dignissim, non dictum tortor ornare. Suspendisse sit amet pharetra quam. Mauris ligula tortor, congue vitae accumsan rutrum, fermentum id mauris. Nulla et lorem vitae metus vulputate semper et vitae nunc. Etiam porta diam vitae diam venenatis vulputate. Phasellus sodales eget justo vitae facilisis. Fusce ultrices tortor quis rutrum maximus. Sed id lacus ac ipsum tempor efficitur. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer feugiat urna sed semper sodales. Curabitur mattis ligula faucibus ipsum aliquam, nec laoreet orci consequat. Mauris facilisis tristique orci, quis lacinia tellus fringilla id. Ut pellentesque sapien tortor, consectetur auctor sem cursus sit amet.

        Nulla porttitor odio velit, vitae euismod mauris tempor ac. Praesent ultricies hendrerit diam id ornare. Vivamus maximus libero eu felis tempor, ut pellentesque dolor laoreet. Nunc malesuada quis augue vel malesuada. Pellentesque molestie libero id vestibulum scelerisque. Donec tempus, urna at accumsan mollis, dui metus mattis quam, in tincidunt est turpis sit amet augue. Aenean non laoreet purus. Pellentesque tempor pharetra mi, scelerisque mattis odio suscipit ut. Etiam quis auctor lorem. Donec pellentesque sapien eget blandit rhoncus. Sed ut enim aliquam, mattis erat eu, ullamcorper orci. Cras eu diam et nunc faucibus hendrerit nec dignissim nulla. Vivamus eget efficitur metus, vel imperdiet sem. Ut ornare ante dapibus pulvinar pulvinar. Quisque in tincidunt metus, id egestas libero.

        Etiam metus leo, pulvinar vitae lorem a, venenatis vestibulum lorem. Phasellus scelerisque lacus eget lectus luctus volutpat. Aenean pellentesque eu nisl vel egestas. Fusce tempor erat magna, in luctus magna laoreet et. Aenean feugiat accumsan nisl, non venenatis tellus imperdiet in. Nullam euismod sapien sed sem placerat pellentesque. Sed ultrices tristique scelerisque.

        Maecenas et tellus nec odio feugiat pellentesque. Pellentesque iaculis facilisis nibh non dapibus. Nunc scelerisque nisi at iaculis ultrices. Maecenas aliquet in massa id commodo. Praesent sapien nisl, dapibus et sem vitae, vestibulum mollis enim. Nullam ut ullamcorper diam. Nam elementum dapibus ligula sit amet placerat.

        Suspendisse eu mauris dolor. Etiam fermentum augue ligula, et dignissim odio efficitur et. Mauris placerat lorem urna, vel tristique velit vulputate vitae. Vestibulum vel sem id odio finibus ultrices sit amet vitae felis. Praesent posuere ultricies erat, nec posuere purus mollis et. Donec et pharetra ipsum. Fusce vulputate nunc eros, sed maximus nisl vulputate eu. Sed aliquet lectus sed libero posuere, sed tristique mauris convallis. Quisque tincidunt risus nec metus euismod eleifend.

        Duis posuere laoreet ultrices. Aenean ut augue et odio mollis accumsan. Aliquam magna augue, semper sed magna sit amet, laoreet fringilla nibh. Vestibulum turpis nunc, semper non odio et, facilisis mollis lacus. Integer odio nunc, condimentum in ornare ac, porta vitae nulla. Vivamus mollis justo mi, at rutrum felis malesuada id. Ut congue, nisl ut ullamcorper convallis, felis dui scelerisque sem, vitae vehicula purus orci eu augue. Quisque leo massa, semper sed porttitor feugiat, tempus sed dolor. Pellentesque vestibulum diam ac nunc laoreet, ac auctor lorem ultrices. Nulla sed velit aliquet, ultricies ligula ut, blandit lectus. Morbi tincidunt consectetur tellus, ut finibus magna. Vivamus ac semper nulla, vitae pulvinar massa. Fusce varius magna non ipsum pharetra auctor vitae efficitur felis. Etiam placerat sit amet erat sit amet imperdiet. Nulla lacus metus, accumsan ut feugiat in, imperdiet sit amet urna. Mauris porttitor turpis massa.

        Donec faucibus sem a erat semper, non cursus nulla pellentesque. Aenean imperdiet arcu vestibulum est facilisis, sed aliquet metus pellentesque. Duis tellus elit, aliquet vitae vehicula a, laoreet ut mi. Pellentesque mollis turpis nisl, eget volutpat nulla sodales sit amet. Donec non quam diam. Proin vel ultrices erat, et malesuada mi. Vestibulum quis orci in justo viverra vehicula. Cras neque ex, tempor nec euismod at, tincidunt lacinia ex. Phasellus tincidunt orci in leo suscipit, et ullamcorper dolor rhoncus.

        Nam mattis sed augue in tempor. Pellentesque sapien ante, tincidunt sit amet placerat non, pulvinar in lorem. Curabitur maximus metus eget orci suscipit sodales. Donec commodo dui eu egestas venenatis. Aliquam sit amet est tincidunt, bibendum sem in, fringilla nibh. Sed nec semper lorem. Integer porttitor orci vel euismod tristique. Fusce bibendum mauris vitae vehicula ullamcorper. Praesent gravida, tellus vitae scelerisque efficitur, mauris lectus ultricies nunc, nec feugiat enim lectus et mauris. Nulla facilisi. Proin at consectetur nibh, bibendum semper dolor. Phasellus nec suscipit metus, nec blandit elit. Quisque vehicula dolor non mattis blandit. Sed tincidunt metus id ipsum gravida lobortis. Aliquam ut semper risus.</p>
    </div>
</body>
</html>
